# Generated by Django 3.2.4 on 2021-07-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='rutcola',
            new_name='rut',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='rutcola',
            new_name='rut',
        ),
    ]
